package texmath.types

class TeXParser {

  val symbols = Map(
    "+" -> ESymbol(Bin, "+"),
    "-" -> ESymbol(Bin, "\u2212"),
    "*" -> ESymbol(Bin, "*"),
    "," -> ESymbol(Pun, ","),
    "." -> ESymbol(Pun, "."),
    ";" -> ESymbol(Pun, ";"),
    ":" -> ESymbol(Pun, ":"),
    "?" -> ESymbol(Pun, "?"),
    ">" -> ESymbol(Rel, ">"),
    "<" -> ESymbol(Rel, "<"),
    "!" -> ESymbol(Ord, "!"),
    "'" -> ESymbol(Ord, "\u02B9"),
    "''" -> ESymbol(Ord, "\u02BA"),
    "'''" -> ESymbol(Ord, "\u2034"),
    "''''" -> ESymbol(Ord, "\u2057"),
    "=" -> ESymbol(Rel, "="),
    ":=" -> ESymbol(Rel, ":="),
    "\\mid" -> ESymbol(Bin, "\u2223"),
    "\\parallel" -> ESymbol(Rel, "\u2225"),
    "\\backslash" -> ESymbol(Bin, "\u2216"),
    "/" -> ESymbol(Bin, "/"),
    "\\setminus" -> ESymbol(Bin, "\\"),
    "\\times" -> ESymbol(Bin, "\u00D7"),
    "\\alpha" -> EIdentifier("\u03B1"),
    "\\beta" -> EIdentifier("\u03B2"),
    "\\chi" -> EIdentifier("\u03C7"),
    "\\delta" -> EIdentifier("\u03B4"),
    "\\Delta" -> ESymbol(Op, "\u0394"),
    "\\epsilon" -> EIdentifier("\u03B5"),
    "\\varepsilon" -> EIdentifier("\u025B"),
    "\\eta" -> EIdentifier("\u03B7"),
    "\\gamma" -> EIdentifier("\u03B3"),
    "\\Gamma" -> ESymbol(Op, "\u0393"),
    "\\iota" -> EIdentifier("\u03B9"),
    "\\kappa" -> EIdentifier("\u03BA"),
    "\\lambda" -> EIdentifier("\u03BB"),
    "\\Lambda" -> ESymbol(Op, "\u039B"),
    "\\mu" -> EIdentifier("\u03BC"),
    "\\nu" -> EIdentifier("\u03BD"),
    "\\omega" -> EIdentifier("\u03C9"),
    "\\Omega" -> ESymbol(Op, "\u03A9"),
    "\\phi" -> EIdentifier("\u03D5"),
    "\\varphi" -> EIdentifier("\u03C6"),
    "\\Phi" -> ESymbol(Op, "\u03A6"),
    "\\pi" -> EIdentifier("\u03C0"),
    "\\Pi" -> ESymbol(Op, "\u03A0"),
    "\\psi" -> EIdentifier("\u03C8"),
    "\\Psi" -> ESymbol(Ord, "\u03A8"),
    "\\rho" -> EIdentifier("\u03C1"),
    "\\sigma" -> EIdentifier("\u03C3"),
    "\\Sigma" -> ESymbol(Op, "\u03A3"),
    "\\tau" -> EIdentifier("\u03C4"),
    "\\theta" -> EIdentifier("\u03B8"),
    "\\vartheta" -> EIdentifier("\u03D1"),
    "\\Theta" -> ESymbol(Op, "\u0398"),
    "\\upsilon" -> EIdentifier("\u03C5"),
    "\\Upsilon" -> EIdentifier("\u03A5"),
    "\\xi" -> EIdentifier("\u03BE"),
    "\\Xi" -> ESymbol(Op, "\u039E"),
    "\\zeta" -> EIdentifier("\u03B6"),
    "\\pm" -> ESymbol(Bin, "\u00B1"),
    "\\mp" -> ESymbol(Bin, "\u2213"),
    "\\triangleleft" -> ESymbol(Bin, "\u22B2"),
    "\\triangleright" -> ESymbol(Bin, "\u22B3"),
    "\\cdot" -> ESymbol(Bin, "\u22C5"),
    "\\star" -> ESymbol(Bin, "\u22C6"),
    "\\ast" -> ESymbol(Bin, "\u002A"),
    "\\times" -> ESymbol(Bin, "\u00D7"),
    "\\div" -> ESymbol(Bin, "\u00F7"),
    "\\circ" -> ESymbol(Bin, "\u2218"),
    "\\bullet" -> ESymbol(Bin, "\u2022"),
    "\\oplus" -> ESymbol(Bin, "\u2295"),
    "\\ominus" -> ESymbol(Bin, "\u2296"),
    "\\otimes" -> ESymbol(Bin, "\u2297"),
    "\\bigcirc" -> ESymbol(Bin, "\u25CB"),
    "\\oslash" -> ESymbol(Bin, "\u2298"),
    "\\odot" -> ESymbol(Bin, "\u2299"),
    "\\land" -> ESymbol(Bin, "\u2227"),
    "\\wedge" -> ESymbol(Bin, "\u2227"),
    "\\lor" -> ESymbol(Bin, "\u2228"),
    "\\vee" -> ESymbol(Bin, "\u2228"),
    "\\cap" -> ESymbol(Bin, "\u2229"),
    "\\cup" -> ESymbol(Bin, "\u222A"),
    "\\sqcap" -> ESymbol(Bin, "\u2293"),
    "\\sqcup" -> ESymbol(Bin, "\u2294"),
    "\\uplus" -> ESymbol(Bin, "\u228E"),
    "\\amalg" -> ESymbol(Bin, "\u2210"),
    "\\bigtriangleup" -> ESymbol(Bin, "\u25B3"),
    "\\bigtriangledown" -> ESymbol(Bin, "\u25BD"),
    "\\dag" -> ESymbol(Bin, "\u2020"),
    "\\dagger" -> ESymbol(Bin, "\u2020"),
    "\\ddag" -> ESymbol(Bin, "\u2021"),
    "\\ddagger" -> ESymbol(Bin, "\u2021"),
    "\\lhd" -> ESymbol(Bin, "\u22B2"),
    "\\rhd" -> ESymbol(Bin, "\u22B3"),
    "\\unlhd" -> ESymbol(Bin, "\u22B4"),
    "\\unrhd" -> ESymbol(Bin, "\u22B5"),
    "\\lt" -> ESymbol(Rel, "<"),
    "\\gt" -> ESymbol(Rel, ">"),
    "\\ne" -> ESymbol(Rel, "\u2260"),
    "\\neq" -> ESymbol(Rel, "\u2260"),
    "\\le" -> ESymbol(Rel, "\u2264"),
    "\\leq" -> ESymbol(Rel, "\u2264"),
    "\\leqslant" -> ESymbol(Rel, "\u2264"),
    "\\ge" -> ESymbol(Rel, "\u2265"),
    "\\geq" -> ESymbol(Rel, "\u2265"),
    "\\geqslant" -> ESymbol(Rel, "\u2265"),
    "\\equiv" -> ESymbol(Rel, "\u2261"),
    "\\ll" -> ESymbol(Rel, "\u226A"),
    "\\gg" -> ESymbol(Rel, "\u226B"),
    "\\doteq" -> ESymbol(Rel, "\u2250"),
    "\\prec" -> ESymbol(Rel, "\u227A"),
    "\\succ" -> ESymbol(Rel, "\u227B"),
    "\\preceq" -> ESymbol(Rel, "\u227C"),
    "\\succeq" -> ESymbol(Rel, "\u227D"),
    "\\subset" -> ESymbol(Rel, "\u2282"),
    "\\supset" -> ESymbol(Rel, "\u2283"),
    "\\subseteq" -> ESymbol(Rel, "\u2286"),
    "\\supseteq" -> ESymbol(Rel, "\u2287"),
    "\\sqsubset" -> ESymbol(Rel, "\u228F"),
    "\\sqsupset" -> ESymbol(Rel, "\u2290"),
    "\\sqsubseteq" -> ESymbol(Rel, "\u2291"),
    "\\sqsupseteq" -> ESymbol(Rel, "\u2292"),
    "\\sim" -> ESymbol(Rel, "\u223C"),
    "\\simeq" -> ESymbol(Rel, "\u2243"),
    "\\approx" -> ESymbol(Rel, "\u2248"),
    "\\cong" -> ESymbol(Rel, "\u2245"),
    "\\Join" -> ESymbol(Rel, "\u22C8"),
    "\\bowtie" -> ESymbol(Rel, "\u22C8"),
    "\\in" -> ESymbol(Rel, "\u2208"),
    "\\ni" -> ESymbol(Rel, "\u220B"),
    "\\owns" -> ESymbol(Rel, "\u220B"),
    "\\propto" -> ESymbol(Rel, "\u221D"),
    "\\vdash" -> ESymbol(Rel, "\u22A2"),
    "\\dashv" -> ESymbol(Rel, "\u22A3"),
    "\\models" -> ESymbol(Rel, "\u22A8"),
    "\\perp" -> ESymbol(Rel, "\u22A5"),
    "\\smile" -> ESymbol(Rel, "\u2323"),
    "\\frown" -> ESymbol(Rel, "\u2322"),
    "\\asymp" -> ESymbol(Rel, "\u224D"),
    "\\notin" -> ESymbol(Rel, "\u2209"),
    "\\gets" -> ESymbol(Rel, "\u2190"),
    "\\leftarrow" -> ESymbol(Rel, "\u2190"),
    "\\to" -> ESymbol(Rel, "\u2192"),
    "\\rightarrow" -> ESymbol(Rel, "\u2192"),
    "\\leftrightarrow" -> ESymbol(Rel, "\u2194"),
    "\\uparrow" -> ESymbol(Rel, "\u2191"),
    "\\downarrow" -> ESymbol(Rel, "\u2193"),
    "\\updownarrow" -> ESymbol(Rel, "\u2195"),
    "\\Leftarrow" -> ESymbol(Rel, "\u21D0"),
    "\\Rightarrow" -> ESymbol(Rel, "\u21D2"),
    "\\Leftrightarrow" -> ESymbol(Rel, "\u21D4"),
    "\\iff" -> ESymbol(Rel, "\u21D4"),
    "\\Uparrow" -> ESymbol(Rel, "\u21D1"),
    "\\Downarrow" -> ESymbol(Rel, "\u21D3"),
    "\\Updownarrow" -> ESymbol(Rel, "\u21D5"),
    "\\mapsto" -> ESymbol(Rel, "\u21A6"),
    "\\longleftarrow" -> ESymbol(Rel, "\u2190"),
    "\\longrightarrow" -> ESymbol(Rel, "\u2192"),
    "\\longleftrightarrow" -> ESymbol(Rel, "\u2194"),
    "\\Longleftarrow" -> ESymbol(Rel, "\u21D0"),
    "\\Longrightarrow" -> ESymbol(Rel, "\u21D2"),
    "\\Longleftrightarrow" -> ESymbol(Rel, "\u21D4"),
    "\\longmapsto" -> ESymbol(Rel, "\u21A6"),
    "\\sum" -> ESymbol(Op, "\u2211"),
    "\\prod" -> ESymbol(Op, "\u220F"),
    "\\bigcap" -> ESymbol(Op, "\u22C2"),
    "\\bigcup" -> ESymbol(Op, "\u22C3"),
    "\\bigwedge" -> ESymbol(Op, "\u22C0"),
    "\\bigvee" -> ESymbol(Op, "\u22C1"),
    "\\bigsqcap" -> ESymbol(Op, "\u2A05"),
    "\\bigsqcup" -> ESymbol(Op, "\u2A06"),
    "\\coprod" -> ESymbol(Op, "\u2210"),
    "\\bigoplus" -> ESymbol(Op, "\u2A01"),
    "\\bigotimes" -> ESymbol(Op, "\u2A02"),
    "\\bigodot" -> ESymbol(Op, "\u2A00"),
    "\\biguplus" -> ESymbol(Op, "\u2A04"),
    "\\int" -> ESymbol(Op, "\u222B"),
    "\\iint" -> ESymbol(Op, "\u222C"),
    "\\iiint" -> ESymbol(Op, "\u222D"),
    "\\oint" -> ESymbol(Op, "\u222E"),
    "\\prime" -> ESymbol(Ord, "\u2032"),
    "\\dots" -> ESymbol(Ord, "\u2026"),
    "\\ldots" -> ESymbol(Ord, "\u2026"),
    "\\cdots" -> ESymbol(Ord, "\u22EF"),
    "\\vdots" -> ESymbol(Ord, "\u22EE"),
    "\\ddots" -> ESymbol(Ord, "\u22F1"),
    "\\forall" -> ESymbol(Op, "\u2200"),
    "\\exists" -> ESymbol(Op, "\u2203"),
    "\\Re" -> ESymbol(Ord, "\u211C"),
    "\\Im" -> ESymbol(Ord, "\u2111"),
    "\\aleph" -> ESymbol(Ord, "\u2135"),
    "\\hbar" -> ESymbol(Ord, "\u210F"),
    "\\ell" -> ESymbol(Ord, "\u2113"),
    "\\wp" -> ESymbol(Ord, "\u2118"),
    "\\emptyset" -> ESymbol(Ord, "\u2205"),
    "\\infty" -> ESymbol(Ord, "\u221E"),
    "\\partial" -> ESymbol(Ord, "\u2202"),
    "\\nabla" -> ESymbol(Ord, "\u2207"),
    "\\triangle" -> ESymbol(Ord, "\u25B3"),
    "\\therefore" -> ESymbol(Pun, "\u2234"),
    "\\angle" -> ESymbol(Ord, "\u2220"),
    "\\diamond" -> ESymbol(Op, "\u22C4"),
    "\\Diamond" -> ESymbol(Op, "\u25C7"),
    "\\lozenge" -> ESymbol(Op, "\u25CA"),
    "\\neg" -> ESymbol(Op, "\u00AC"),
    "\\lnot" -> ESymbol(Ord, "\u00AC"),
    "\\bot" -> ESymbol(Ord, "\u22A5"),
    "\\top" -> ESymbol(Ord, "\u22A4"),
    "\\square" -> ESymbol(Ord, "\u25AB"),
    "\\Box" -> ESymbol(Op, "\u25A1"),
    "\\wr" -> ESymbol(Ord, "\u2240"),
    "\\!" -> ESpace("-0.167em"),
    "\\," -> ESpace("0.167em"),
    "\\>" -> ESpace("0.222em"),
    "\\:" -> ESpace("0.222em"),
    "\\;" -> ESpace("0.278em"),
    "~" -> ESpace("0.333em"),
    "\\quad" -> ESpace("1em"),
    "\\qquad" -> ESpace("2em"),
    "\\arccos" -> EMathOperator("arccos"),
    "\\arcsin" -> EMathOperator("arcsin"),
    "\\arctan" -> EMathOperator("arctan"),
    "\\arg" -> EMathOperator("arg"),
    "\\cos" -> EMathOperator("cos"),
    "\\cosh" -> EMathOperator("cosh"),
    "\\cot" -> EMathOperator("cot"),
    "\\coth" -> EMathOperator("coth"),
    "\\csc" -> EMathOperator("csc"),
    "\\deg" -> EMathOperator("deg"),
    "\\det" -> EMathOperator("det"),
    "\\dim" -> EMathOperator("dim"),
    "\\exp" -> EMathOperator("exp"),
    "\\gcd" -> EMathOperator("gcd"),
    "\\hom" -> EMathOperator("hom"),
    "\\inf" -> EMathOperator("inf"),
    "\\ker" -> EMathOperator("ker"),
    "\\lg" -> EMathOperator("lg"),
    "\\lim" -> EMathOperator("lim"),
    "\\liminf" -> EMathOperator("liminf"),
    "\\limsup" -> EMathOperator("limsup"),
    "\\ln" -> EMathOperator("ln"),
    "\\log" -> EMathOperator("log"),
    "\\max" -> EMathOperator("max"),
    "\\min" -> EMathOperator("min"),
    "\\Pr" -> EMathOperator("Pr"),
    "\\sec" -> EMathOperator("sec"),
    "\\sin" -> EMathOperator("sin"),
    "\\sinh" -> EMathOperator("sinh"),
    "\\sup" -> EMathOperator("sup"),
    "\\tan" -> EMathOperator("tan"),
    "\\tanh" -> EMathOperator("tanh")    
  )
}